name: GeoJSON Parent Processing

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Debug directory contents
        run: ls -la
      - name: Check input file sizes
        run: ls -lh geoBoundaries-IND-ADM1_simplified.geojson geoBoundaries-IND-ADM2_simplified.geojson
      - name: Install dependencies
        run: npm install
      - name: Run streamed parent linker
        run: node streamLinkParent.js
      - name: Upload GeoJSON
        uses: actions/upload-artifact@v4
        with:
          name: geojson-output
          path: adm1_with_parent_streamed.geojson